esphome:
  name: attic_fan
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

api:

ota:

i2c:
  scan: False

sensor:
  - platform: bmp280
    temperature:
      name: "Attic Temp"
      oversampling: 16x
      id: attic_fan_temp
    pressure:
      name: "Attic Pressure"
      id: attic_fan_press
    address: 0x76
    update_interval: 60s

climate:
  - platform: bang_bang
    name: "Attic Fan"
    sensor: attic_fan_temp
    visual:
      min_temperature: 30
      max_temperature: 60
      temperature_step: 1
    default_target_temperature_low: 42
    default_target_temperature_high: 43
    cool_action:
      - switch.turn_on: attic_fan_relay
    idle_action:
      - switch.turn_off: attic_fan_relay

switch:
  - platform: gpio
    name: "Attic Fan Relay"
    pin: D8
    id: attic_fan_relay
    restore_mode: ALWAYS_OFF