esphome:
  name: attic
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

api:

ota:

i2c:
  # sda: 4
  # scl: 5
  scan: False

sensor:
  - platform: bmp085
    address: 0x77
    temperature:
      name: "Attic Temperature"
      id: attic_temp
    pressure:
      name: "Attic Pressure"
      id: attic_press
    update_interval: 60s