esphome:
  name: backporch
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
                               
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

api:

ota:

i2c:
  scan: False

sensor:
  - platform: bme280
    temperature:
      id: backporch_temp
      name: "Backporch Temp"
      oversampling: 16x
    pressure:
      id: backporch_press
      name: "Backporch Pressure"
    humidity:
      id: "backporch_humid"
      name: "Backporch Humidity"
    address: 0x76
    update_interval: 60s