substitutions:
  device_name: crawl_main
  display_name: Crawlspace Main

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
                               
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

api:

ota:

i2c:
  scan: False

# switch:
#   - platform: gpio
#     pin: D0
#     name: "Crawlspace Back Lights"

light:
  - platform: monochromatic
    name: ${display_name} Lights
    output: ${device_name}_pwm

output:
  - platform: esp8266_pwm
    id: ${device_name}_pwm
    pin: D0

sensor:
  - platform: bme280
    temperature:
      id: ${device_name}_temp
      name: ${display_name} Temp
      oversampling: 16x
    pressure:
      id: ${device_name}_press
      name: ${display_name} Pressure
    humidity:
      id: ${device_name}_humid
      name: ${display_name} Humidity
    address: 0x76
    update_interval: 60s