esphome:
  name: crawlspace
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
                               
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

api:

ota:

#D1 - br/wt - scl - GPIO5
#D2 - brown - sda - GPIO4
i2c:
  # sda: 4
  # scl: 5
  scan: False

sensor:
  - platform: bme280
    temperature:
      id: "crawlspace_temp"
      name: "Crawlspace Temperature"
      oversampling: 16x
    pressure:
      id: "crawlspace_press"
      name: "Crawlspace Pressure"
    humidity:
      id: "crawlspace_humid"
      name: "Crawlspace Humidity"
    address: 0x76
    update_interval: 60s