substitutions:
  node_name: esp_thermostat_nook
  node_friendly_name: "Nook Thermostat"

packages:
  esp_common: !include shared/esp__common_core.yaml
  esp_thermostat_common: !include shared/esp_thermostat_common_config.yaml
  esp_thermostat_common_controller: !include shared/esp_thermostat_common_controller_config.yaml

sensor:
  # Phototransistor ADC sensor
  - platform: adc
    id: adc_sensor_phototransistor
    name: ${node_friendly_name} Phototransistor ADC
    pin: 32
    attenuation: 11db
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 3
          send_first_at: 1
    on_value:
      then:
        - lambda: |-
            const float display_brightness = id(adc_sensor_phototransistor).state / 3.9;
            id(main_lcd)->set_brightness(display_brightness);
  # NTC thermistor ADC sensor
  - platform: adc
    id: adc_sensor_thermistor
    name: ${node_friendly_name} Thermistor ADC
    pin: 34
    internal: true
    update_interval: never
  # NTC thermistor resistance sensor
  - platform: resistance
    id: thermistor_sensor
    name: ${node_friendly_name} NTC Thermistor Resistance
    sensor: adc_sensor_thermistor
    configuration: DOWNSTREAM
    reference_voltage: 0.815V
    resistor: 10kOhm
    internal: true
  # NTC thermistor sensor
  - platform: ntc
    id: esp_thermostat_thermistor_temperature
    name: ${node_friendly_name} NTC Thermistor Temperature
    sensor: thermistor_sensor
    calibration:
      b_constant: 3380
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      - sliding_window_moving_average:
          window_size: 8
          send_every: 1
          send_first_at: 1
  # DHT22 sensor
  # - platform: dht
  #   pin: GPIO23
  #   model: DHT22
  #   temperature:
  #     id: esp_thermostat_dht22_temperature
  #     name: ${node_friendly_name} DHT22 Temperature
  #     filters:
  #       - offset: -1.3
  #   humidity:
  #     id: esp_thermostat_dht22_humidity
  #     name: ${node_friendly_name} DHT22 Humidity
  #   update_interval: 15s
  # BME280 sensor
  - platform: bme280
    address: 0x76
    temperature:
      id: esp_thermostat_bme280_temperature
      name: ${node_friendly_name} BME280 Temperature
      filters:
        - offset: -0.3
    humidity:
      id: esp_thermostat_bme280_humidity
      name: ${node_friendly_name} BME280 Humidity
    pressure:
      id: esp_thermostat_bme280_pressure
      name: ${node_friendly_name} BME280 Pressure
    update_interval: 15s
  # SHTC3 sensor
  - platform: shtcx
    temperature:
      id: esp_thermostat_shtcx_temperature
      name: ${node_friendly_name} SHTC3 Temperature
      filters:
        - offset: -1.3
    humidity:
      id: esp_thermostat_shtcx_humidity
      name: ${node_friendly_name} SHTC3 Humidity
    update_interval: 15s

display:
  - platform: ssd1325_spi
    id: main_lcd
    model: "SSD1325 128x64"
    cs_pin: GPIO15
    dc_pin: GPIO16
    reset_pin: GPIO17
    pages:
      - id: main_screen
        lambda: 'esp32_thermostat::draw_main_screen(&it);'
      - id: setpoint_screen
        lambda: 'esp32_thermostat::draw_setpoint_screen(&it);'
      - id: mode_screen
        lambda: 'esp32_thermostat::draw_mode_screen(&it);'
      - id: rooms_screen
        lambda: 'esp32_thermostat::draw_rooms_screen(&it);'
      - id: sensors_screen
        lambda: |-
          esp32_thermostat::draw_footer(&it);

          it.printf(0, 0, id(thermostat_small), id(color_mode), TextAlign::TOP_LEFT, "On-board sensor data:");

          it.printf(0, 12, id(thermostat_small), id(color_highlight), TextAlign::TOP_LEFT, "BME280:");
          it.printf(0, 22, id(thermostat_small), id(color_highlight), TextAlign::TOP_LEFT, "SHTC3:");
          // it.printf(0, 32, id(thermostat_small), id(color_highlight), TextAlign::TOP_LEFT, "DHT22:");
          // it.printf(0, 42, id(thermostat_small), id(color_highlight), TextAlign::TOP_LEFT, "TMP117:");
          it.printf(0, 32, id(thermostat_small), id(color_highlight), TextAlign::TOP_LEFT, "Thermistor:");

          it.printf(it.get_width(), 12, id(thermostat_small), id(color_highlight), TextAlign::TOP_RIGHT, "%.1f°  %.1f%%", id(esp_thermostat_bme280_temperature).state * 1.8 + 32, id(esp_thermostat_bme280_humidity).state);
          it.printf(it.get_width(), 22, id(thermostat_small), id(color_highlight), TextAlign::TOP_RIGHT, "%.1f°  %.1f%%", id(esp_thermostat_shtcx_temperature).state * 1.8 + 32, id(esp_thermostat_shtcx_humidity).state);
          // it.printf(it.get_width(), 32, id(thermostat_small), id(color_highlight), TextAlign::TOP_RIGHT, "%.1f°  %.1f%%", id(esp_thermostat_dht22_temperature).state * 1.8 + 32, id(esp_thermostat_dht22_humidity).state);
          // it.printf(it.get_width() - 37, 42, id(thermostat_small), id(color_highlight), TextAlign::TOP_RIGHT, "%.1f°", id(esp_thermostat_tmp117_temperature).state * 1.8 + 32);
          it.printf(it.get_width() - 37, 32, id(thermostat_small), id(color_highlight), TextAlign::TOP_RIGHT, "%.1f°", id(esp_thermostat_thermistor_temperature).state * 1.8 + 32);
