substitutions:
  display_name: 1stFloor

esphome:
  name: homemonitor
  platform: ESP32
  board: featheresp32
  includes:
    - hpma115c0.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  id: esp_api
  password: !secret api_password

ota:
  password: !secret ota_password

# captive_portal:

# Enable logging
logger:

i2c:
  id: i2c_bus
  frequency: 400kHz
  sda: 23
  scl: 22
  scan: True

#gpio21 zmod_reset
#gpio 19 zmod_int0
#gpio 18 zmod_int1
#gpio5 dustpwr
#gpio17 neopixel
#gpio16 dusttx
#gpio4 dustrx

# switch:
#   - platform: gpio
#     name: "Honeywell HPMA115C0 Power"
#     pin: 5

#   - platform: gpio
#     name: "Renesas ZMOD INT0"
#     pin:
#       number: 19
#       inverted: True #?
#       mode: INPUT_PULLUP #?

#   - platform: gpio
#     name: "Renesas ZMOD INT1"
#     pin:
#       number: 18
#       inverted: True #?
#       mode: INPUT_PULLUP #?
bme680_bsec:
    # i2c address
    # -----------
    # Common values are:
    # - 0x76
    # - 0x77
    # Default: 0x76
    address: 0x77

    # Temperature offset
    # ------------------
    # Useful if device is in enclosure and reads too high
    # Default: 0
    temperature_offset: 0

    # IAQ calculation mode
    # --------------------
    # Available options:
    # - static (for fixed position devices)
    # - mobile (for on person or other moveable devices)
    # Default: static
    iaq_mode: static

    # Sample rate
    # -----------
    # Available options:
    # - lp (low power - samples every 3 seconds)
    # - ulp (ultra low power - samples every 5 minutes)
    # Default: lp
    sample_rate: lp

    # Interval at which to save BSEC state
    # ------------------------------------
    # Default: 6h
    state_save_interval: 6h

sensor:
  # - platform: bme680
  #   temperature:
  #     id: bme680_temp
  #     name: ${display_name} Temperature
  #     oversampling: 16x
  #   pressure:
  #     name: ${display_name} Pressure
  #   humidity:
  #     id: bme680_humid
  #     name: ${display_name} Humidity
  #   gas_resistance:
  #     name: ${display_name} Gas Resistance
  #   address: 0x77
  #   update_interval: 20s

  - platform: custom
    lambda: |-
      auto hpm = new Hpma115C0Component(20000, id(uart_bus));
      App.register_component(hpm);
      return {hpm->pm_1_sensor, hpm->pm_2_5_sensor, hpm->pm_4_sensor, hpm->pm_10_sensor};
    sensors:
      - name: ${display_name} PM <1
        unit_of_measurement: "μg/m³"
        icon: "mdi:vanish"
      - name: ${display_name} PM <2.5
        unit_of_measurement: "μg/m³"
        icon: "mdi:vanish"
      - name: ${display_name} PM <4
        unit_of_measurement: "μg/m³"
        icon: "mdi:vanish"
      - name: ${display_name} PM <10
        unit_of_measurement: "μg/m³"
        icon: "mdi:vanish"

  - platform: sgp40
    name: ${display_name} VOC Index
    compensation:
      temperature_source: bme680_temp
      humidity_source: bme680_humid
    store_baseline: True
    update_interval: 5s

  - platform: bme680_bsec
    temperature:
      id: bme680_temp
      # Temperature in °C
      name: "BME680 Temperature"
      filters:
        - median
    pressure:
      # Pressure in hPa
      name: "BME680 Pressure"
      filters:
        - median
    humidity:
      id: bme680_humid
      # Relative humidity %
      name: "BME680 Humidity"
      filters:
        - median
    gas_resistance:
      # Gas resistance in Ω
      name: "BME680 Gas Resistance"
      filters:
        - median
    iaq:
      # Indoor air quality value
      name: "BME680 IAQ"
      filters:
        - median
    iaq_accuracy:
      # IAQ accuracy as a numeric value of 0, 1, 2, 3
      name: "BME680 Numeric IAQ Accuracy"
    co2_equivalent:
      # CO2 equivalent estimate in ppm
      name: "BME680 CO2 Equivalent"
      filters:
        - median
    breath_voc_equivalent:
      # Volatile organic compounds equivalent estimate in ppm
      name: "BME680 Breath VOC Equivalent"
      filters:
        - median

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "BME680 IAQ Accuracy"    
web_server:
  port: 80
#renesas 4410

# light:
#   - platform: neopixelbus
#     type: GRB
#     pin: GPIO17
#     num_leds: 1
#     name: "NeoPixel Light"

uart:
  id: uart_bus
  rx_pin: GPIO4
  tx_pin: GPIO16
  baud_rate: 9600
