esphome:
  name: neotest
  includes:
    - sngcja5.h

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "dfffe193b7f937d02aae263dd017811c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Neotest Fallback Hotspot"
    password: "nPpkxdroYBcM"

captive_portal:

i2c:
  scan: True
  frequency: 400kHz

binary_sensor:
  - platform: gpio
    id: pir_motion
    name: Motion Detection
    pin: D5

light:
  - platform: neopixelbus
    type: RGBW
    variant: SK6812
    pin: D4
    num_leds: 3
    name: Neopixels
     
sensor:
  - platform: custom
    lambda: |-
      auto sngcja5 = new Sngcja5Component(15000);
      App.register_component(sngcja5);
      return {sngcja5->pm1_sensor, sngcja5->pm2_5_sensor,  sngcja5->pm10_sensor};
    sensors:
      - name: PM <1
        unit_of_measurement: "μg/m³"
        icon: "mdi:vanish"
      - name: PM <2.5
        unit_of_measurement: "μg/m³"
        icon: "mdi:vanish"
      - name: PM <10
        unit_of_measurement: "μg/m³"
        icon: "mdi:vanish"