#sudo docker run --rm -v "${PWD}":/config --device=/dev/ttyUSB0 -it esphome/esphome stairs.yaml run

substitutions:
  device_name: stairs
  display_name: Stairs

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s
   
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
                               
logger:
  level: INFO

api:
  
ota:

web_server:
  port: 80

output:
  - platform: ledc
    pin: GPIO4
    id: ${device_name}_step0
  - platform: ledc
    pin: GPIO5
    id: ${device_name}_step1
  - platform: ledc
    pin: GPIO12
    id: ${device_name}_step2
  - platform: ledc
    pin: GPIO13
    id: ${device_name}_step3
  - platform: ledc
    pin: GPIO14
    id: ${device_name}_step4
  - platform: ledc
    pin: GPIO15
    id: ${device_name}_step5
  - platform: ledc
    pin: GPIO16
    id: ${device_name}_step6
  - platform: ledc
    pin: GPIO17
    id: ${device_name}_step7
  - platform: ledc
    pin: GPIO18
    id: ${device_name}_step8
  - platform: ledc
    pin: GPIO19
    id: ${device_name}_step9
  - platform: ledc
    pin: GPIO21
    id: ${device_name}_step10
  - platform: ledc
    pin: GPIO22
    id: ${device_name}_step11
  - platform: ledc
    pin: GPIO23
    id: ${device_name}_step12
  - platform: ledc
    pin: GPIO25
    id: ${device_name}_step13
  - platform: ledc
    pin: GPIO26
    id: ${device_name}_step14

light:
  - platform: monochromatic
    id: s0
    name: ${display_name} 1 (bottom)
    output: ${device_name}_step0
  - platform: monochromatic
    id: s1
    name: ${display_name} 2
    output: ${device_name}_step1
  - platform: monochromatic
    id: s2
    name: ${display_name} 3
    output: ${device_name}_step2
  - platform: monochromatic
    id: s3
    name: ${display_name} 4
    output: ${device_name}_step3
  - platform: monochromatic
    id: s4
    name: ${display_name} 5
    output: ${device_name}_step4
  - platform: monochromatic
    id: s5
    name: ${display_name} 6
    output: ${device_name}_step5
  - platform: monochromatic
    id: s6
    name: ${display_name} 7
    output: ${device_name}_step6
  - platform: monochromatic
    id: s7
    name: ${display_name} 8
    output: ${device_name}_step7
  - platform: monochromatic
    id: s8
    name: ${display_name} 9
    output: ${device_name}_step8
  - platform: monochromatic
    id: s9
    name: ${display_name} 10
    output: ${device_name}_step9
  - platform: monochromatic
    id: s10
    name: ${display_name} 11
    output: ${device_name}_step10
  - platform: monochromatic
    id: s11
    name: ${display_name} 12
    output: ${device_name}_step11
  - platform: monochromatic
    id: s12
    name: ${display_name} 13
    output: ${device_name}_step12
  - platform: monochromatic
    id: s13
    name: ${display_name} 14
    output: ${device_name}_step13
  - platform: monochromatic
    id: s14
    name: ${display_name} 15 (top)
    output: ${device_name}_step14

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO34
      mode: INPUT_PULLUP
      inverted: yes
    id: ${device_name}_button_down
    device_class: light
    on_click:
      then:
        - light.dim_relative:
            id: s0
            relative_brightness: -5%
        - light.dim_relative:
            id: s1
            relative_brightness: -5%
        - light.dim_relative:
            id: s2
            relative_brightness: -5%
        - light.dim_relative:
            id: s3
            relative_brightness: -5%
        - light.dim_relative:
            id: s4
            relative_brightness: -5%
        - light.dim_relative:
            id: s5
            relative_brightness: -5%
        - light.dim_relative:
            id: s6
            relative_brightness: -5%
        - light.dim_relative:
            id: s7
            relative_brightness: -5%
        - light.dim_relative:
            id: s8
            relative_brightness: -5%
        - light.dim_relative:
            id: s9
            relative_brightness: -5%
        - light.dim_relative:
            id: s10
            relative_brightness: -5%
        - light.dim_relative:
            id: s11
            relative_brightness: -5%
        - light.dim_relative:
            id: s12
            relative_brightness: -5%
        - light.dim_relative:
            id: s13
            relative_brightness: -5%
        - light.dim_relative:
            id: s14
            relative_brightness: -5%
  - platform: gpio
    pin:
      number: GPIO35
      mode: INPUT_PULLUP
      inverted: yes
    id: ${device_name}_button_up
    device_class: light
    on_click:
      then:
        - light.dim_relative:
            id: s0
            relative_brightness: 5%
        - light.dim_relative:
            id: s1
            relative_brightness: 5%
        - light.dim_relative:
            id: s2
            relative_brightness: 5%
        - light.dim_relative:
            id: s3
            relative_brightness: 5%
        - light.dim_relative:
            id: s4
            relative_brightness: 5%
        - light.dim_relative:
            id: s5
            relative_brightness: 5%
        - light.dim_relative:
            id: s6
            relative_brightness: 5%
        - light.dim_relative:
            id: s7
            relative_brightness: 5%
        - light.dim_relative:
            id: s8
            relative_brightness: 5%
        - light.dim_relative:
            id: s9
            relative_brightness: 5%
        - light.dim_relative:
            id: s10
            relative_brightness: 5%
        - light.dim_relative:
            id: s11
            relative_brightness: 5%
        - light.dim_relative:
            id: s12
            relative_brightness: 5%
        - light.dim_relative:
            id: s13
            relative_brightness: 5%
        - light.dim_relative:
            id: s14
            relative_brightness: 5%
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: yes
    id: ${device_name}_button_toggle
    device_class: light
    on_click:
      then:
        - lambda: |-
              static LightState* lights[]={id(s0),id(s1),id(s2),id(s3),id(s4),id(s5),id(s6),id(s7),id(s8),id(s9),id(s10),id(s11),id(s12),id(s13),id(s14)};
              for (int i {0}; i <= 14; i++) {
                auto call = lights[i]->toggle();
                call.set_transition_length(1000 + (100 * i));
                call.perform();
              }