#sudo docker run --rm -v "${PWD}":/config --device=/dev/ttyUSB0 -it esphome/esphome stairs.yaml run

substitutions:
  device_name: stairs
  display_name: Stairs

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s
   
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
                               
logger:
  level: INFO
api:
  services:
    - service: steps_fade
      then:
        - script.execute: fade
    - service: steps_brighten
      then:
        - script.execute: brighten
    - service: steps_darken
      then:
        - script.execute: darken
  
ota:

web_server:
  port: 80

output:
  - platform: ledc
    pin: GPIO4
    id: ${device_name}_step0
  - platform: ledc
    pin: GPIO5
    id: ${device_name}_step1
  - platform: ledc
    pin: GPIO12
    id: ${device_name}_step2
  - platform: ledc
    pin: GPIO13
    id: ${device_name}_step3
  - platform: ledc
    pin: GPIO14
    id: ${device_name}_step4
  - platform: ledc
    pin: GPIO15
    id: ${device_name}_step5
  - platform: ledc
    pin: GPIO16
    id: ${device_name}_step6
  - platform: ledc
    pin: GPIO17
    id: ${device_name}_step7
  - platform: ledc
    pin: GPIO18
    id: ${device_name}_step8
  - platform: ledc
    pin: GPIO19
    id: ${device_name}_step9
  - platform: ledc
    pin: GPIO21
    id: ${device_name}_step10
  - platform: ledc
    pin: GPIO22
    id: ${device_name}_step11
  - platform: ledc
    pin: GPIO23
    id: ${device_name}_step12
  - platform: ledc
    pin: GPIO25
    id: ${device_name}_step13
  - platform: ledc
    pin: GPIO26
    id: ${device_name}_step14

light:
  - platform: monochromatic
    id: step0
    name: ${display_name} 01 (bottom)
    output: ${device_name}_step0
  - platform: monochromatic
    id: step1
    name: ${display_name} 02
    output: ${device_name}_step1
  - platform: monochromatic
    id: step2
    name: ${display_name} 03
    output: ${device_name}_step2
  - platform: monochromatic
    id: step3
    name: ${display_name} 04
    output: ${device_name}_step3
  - platform: monochromatic
    id: step4
    name: ${display_name} 05
    output: ${device_name}_step4
  - platform: monochromatic
    id: step5
    name: ${display_name} 06
    output: ${device_name}_step5
  - platform: monochromatic
    id: step6
    name: ${display_name} 07
    output: ${device_name}_step6
  - platform: monochromatic
    id: step7
    name: ${display_name} 08
    output: ${device_name}_step7
  - platform: monochromatic
    id: step8
    name: ${display_name} 09
    output: ${device_name}_step8
  - platform: monochromatic
    id: step9
    name: ${display_name} 10
    output: ${device_name}_step9
  - platform: monochromatic
    id: step10
    name: ${display_name} 11
    output: ${device_name}_step10
  - platform: monochromatic
    id: step11
    name: ${display_name} 12
    output: ${device_name}_step11
  - platform: monochromatic
    id: step12
    name: ${display_name} 13
    output: ${device_name}_step12
  - platform: monochromatic
    id: step13
    name: ${display_name} 14
    output: ${device_name}_step13
  - platform: monochromatic
    id: step14
    name: ${display_name} 15 (top)
    output: ${device_name}_step14

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO34
      mode: INPUT_PULLUP
      inverted: yes
    id: ${device_name}_button_down
    device_class: light
    on_click:
      then:
        - script.execute: darken
  - platform: gpio
    pin:
      number: GPIO35
      mode: INPUT_PULLUP
      inverted: yes
    id: ${device_name}_button_up
    device_class: light
    on_click:
      then:
        - script.execute: brighten
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: yes
    id: ${device_name}_button_toggle
    device_class: light
    on_click:
      then:
        - script.execute: fade

script:
  - id: fade
    then:
      - lambda: |-
          static LightState* lights[]={id(step0),id(step1),id(step2),id(step3),id(step4),id(step5),id(step6),id(step7),id(step8),id(step9),id(step10),id(step11),id(step12),id(step13),id(step14)};
          for (int i {0}; i <= 14; i++) {
            auto call = lights[i]->toggle();
            call.set_transition_length(1000 + (150 * i));
            call.perform();
          }
  - id: fade_on_bottom_up
    then:
      - lambda: |-
          static LightState* lights[]={id(step0),id(step1),id(step2),id(step3),id(step4),id(step5),id(step6),id(step7),id(step8),id(step9),id(step10),id(step11),id(step12),id(step13),id(step14)};
          for (int i {0}; i <= 14; i++) {
            auto call = lights[i]->turn_on();
            call.set_transition_length(1000 + (150 * i));
            call.perform();
          }
  - id: fade_on_top_down
    then:
      - lambda: |-
          static LightState* lights[]={id(step0),id(step1),id(step2),id(step3),id(step4),id(step5),id(step6),id(step7),id(step8),id(step9),id(step10),id(step11),id(step12),id(step13),id(step14)};
          for (int i {14}; i >= 0; i++) {
            auto call = lights[i]->turn_on();
            call.set_transition_length(1000 + (150 * i));
            call.perform();
          }
  - id: fade_off_bottom_up
    then:
      - lambda: |-
          static LightState* lights[]={id(step0),id(step1),id(step2),id(step3),id(step4),id(step5),id(step6),id(step7),id(step8),id(step9),id(step10),id(step11),id(step12),id(step13),id(step14)};
          for (int i {0}; i <= 14; i++) {
            auto call = lights[i]->turn_off();
            call.set_transition_length(1000 + (150 * i));
            call.perform();
          }
  - id: fade_off_top_down
    then:
      - lambda: |-
          static LightState* lights[]={id(step0),id(step1),id(step2),id(step3),id(step4),id(step5),id(step6),id(step7),id(step8),id(step9),id(step10),id(step11),id(step12),id(step13),id(step14)};
          for (int i {14}; i >= 0; i++) {
            auto call = lights[i]->turn_off();
            call.set_transition_length(1000 + (150 * i));
            call.perform();
          }
  - id: darken
    then:
      - light.dim_relative:
          id: step0
          relative_brightness: -5%
      - light.dim_relative:
          id: step1
          relative_brightness: -5%
      - light.dim_relative:
          id: step2
          relative_brightness: -5%
      - light.dim_relative:
          id: step3
          relative_brightness: -5%
      - light.dim_relative:
          id: step4
          relative_brightness: -5%
      - light.dim_relative:
          id: step5
          relative_brightness: -5%
      - light.dim_relative:
          id: step6
          relative_brightness: -5%
      - light.dim_relative:
          id: step7
          relative_brightness: -5%
      - light.dim_relative:
          id: step8
          relative_brightness: -5%
      - light.dim_relative:
          id: step9
          relative_brightness: -5%
      - light.dim_relative:
          id: step10
          relative_brightness: -5%
      - light.dim_relative:
          id: step11
          relative_brightness: -5%
      - light.dim_relative:
          id: step12
          relative_brightness: -5%
      - light.dim_relative:
          id: step13
          relative_brightness: -5%
      - light.dim_relative:
          id: step14
          relative_brightness: -5%
  - id: brighten
    then:
      - light.dim_relative:
          id: step0
          relative_brightness: 5%
      - light.dim_relative:
          id: step1
          relative_brightness: 5%
      - light.dim_relative:
          id: step2
          relative_brightness: 5%
      - light.dim_relative:
          id: step3
          relative_brightness: 5%
      - light.dim_relative:
          id: step4
          relative_brightness: 5%
      - light.dim_relative:
          id: step5
          relative_brightness: 5%
      - light.dim_relative:
          id: step6
          relative_brightness: 5%
      - light.dim_relative:
          id: step7
          relative_brightness: 5%
      - light.dim_relative:
          id: step8
          relative_brightness: 5%
      - light.dim_relative:
          id: step9
          relative_brightness: 5%
      - light.dim_relative:
          id: step10
          relative_brightness: 5%
      - light.dim_relative:
          id: step11
          relative_brightness: 5%
      - light.dim_relative:
          id: step12
          relative_brightness: 5%
      - light.dim_relative:
          id: step13
          relative_brightness: 5%
      - light.dim_relative:
          id: step14
          relative_brightness: 5%
