# sudo docker run --rm -v "${PWD}":/config --device=/dev/ttyUSB0 -it esphome/esphome:dev thermostat1.yaml run

# this thermostat using wroom module

substitutions:
  node_name: "thermostat1"
  node_friendly_name: "Downstairs Thermostat"
  oled_dc_pin: GPIO16
  oled_reset_pin: GPIO17

<<: !include thermostat.common.yaml