#sudo docker run --rm -v "${PWD}":/config --device=/dev/ttyUSB0 -it esphome/esphome servo_test.yaml run

substitutions:
  display_name: VentTestBed

esphome:
  name: ventbed
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
                               
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

api:

ota:

servo:
  - id: vent
    output: pwm_output
    max_level: 11.2%
    min_level: 2.5%

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D1
    frequency: 50 Hz

binary_sensor:
  - platform: gpio
    id: open_button
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: yes
    on_click:
      then:
      - servo.write:
          id: vent
          level: 100%
  - platform: gpio
    id: close_button
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: yes
    on_click:
      then:
      - servo.write:
          id: vent
          level: -100%


light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D4
    num_leds: 3
    rgb_order: GRB
    name: Neopixels
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 5s      # defaults to 1s
          update_interval: 1s
      - addressable_rainbow:
          name: Rainbow Effect
