#sudo docker run --rm -v "${PWD}":/config --device=/dev/ttyUSB0 -it esphome/esphome backporch.yaml run


esphome:
  name: printer_gold
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
                               
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

api:

ota:

i2c:
  scan: False

sensor:
  - platform: bme280
    temperature:
      id: printer_gold_temp
      name: "Goldenchild Chamber Temp"
      oversampling: 16x
    pressure:
      id: printer_gold_press
      name: "Goldenchild Chamber Pressure"
    humidity:
      id: printer_gold_humid
      name: "Goldenchild Chamber Humidity"
    address: 0x76
    update_interval: 60s

