#sudo docker run --rm -v "${PWD}":/config --device=/dev/ttyUSB0 -it esphome/esphome wemos_oled_test.yaml run
#sudo docker run --rm -v "${PWD}":/config --device=/dev/ttyUSB0 -it esphome/esphome wemos_oled_test.yaml logs

substitutions:
  device_name: wemos_oled_test
  display_name: OLEDtest

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
                               
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

api:

ota:

time:
  - platform: homeassistant
    id: esptime

spi:
  clk_pin: D5
  mosi_pin: D7

font:
  - file: "resources/Helvetica.ttf"
    id: font1
    size: 32

display:
  - platform: ssd1325_spi
    model: "SSD1325 128x64"
    reset_pin: D0
    cs_pin: D8
    dc_pin: D1
    update_interval: 1s
    lambda: |-
      // Print time in HH:MM format
      it.strftime(0, 0, id(font1), "%r", id(esptime).now());